<a href="https://colab.research.google.com/github/hermesfeet/ML-Learning/blob/master/Polynomial_Regression_%2B_Regularized_Linear_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Polynomial Regression for Curves and Waves

For anything better than a straight line, like a quadratic equation

In [0]:
import numpy as np
m = 500
X = 7 * np.random.rand(m,1) - 5
y = 0.5 * X**2 + X + 4 + np.random.randn(m,1)
# This is the training set around the poly equation

In [6]:
from sklearn.preprocessing import PolynomialFeatures
poly_features = PolynomialFeatures(degree=2, include_bias=False)
X_poly = poly_features.fit_transform(X)
X[0]
X_poly[0]

array([-2.4689032 ,  6.09548303])

In [8]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_poly, y)
lin_reg.intercept_, lin_reg.coef_
# Note the predicted equation 0.49 X^2 + 0.98*X + 3.997 is close to the equation above

(array([3.99695228]), array([[0.98605922, 0.49747789]]))

In [10]:
# Same with higher degree, to overfit

from sklearn.preprocessing import PolynomialFeatures
poly_features = PolynomialFeatures(degree=5, include_bias=False)
X_poly = poly_features.fit_transform(X)
X[0]
X_poly[0]


array([ -2.4689032 ,   6.09548303, -15.04915756,  37.15491331,
       -91.73188447])

In [11]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_poly, y)
lin_reg.intercept_, lin_reg.coef_

(array([4.09316612]),
 array([[ 1.08343897e+00,  4.56099427e-01, -3.89064807e-02,
         -8.50556824e-03, -6.31388800e-04]]))

In [12]:
# Lasso REgression example - LR automaticall performs feature selection and outputs a sparse model
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.1)
lasso_reg.fit(X,y)
lasso_reg.predict([[1.5]])

array([4.07727991])